import { getDatabase } from '../database'
import { app } from 'electron'
import { join } from 'path'
import { mkdirSync, writeFileSync } from 'fs'
import { DISCIPLINE_LABELS } from '@common/types/intel'
import log from 'electron-log'

export class MemoryService {
  private memoryDir: string

  constructor() {
    this.memoryDir = join(app.getPath('home'), '.heimdall', 'memory')
  }

  generateDailySummary(date?: Date): string {
    const target = date || new Date()
    const dateStr = target.toISOString().split('T')[0]
    const startOfDay = new Date(dateStr + 'T00:00:00Z').getTime()
    const endOfDay = startOfDay + 24 * 60 * 60 * 1000

    const db = getDatabase()

    const total = (
      db.prepare('SELECT COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ?').get(startOfDay, endOfDay) as { count: number }
    ).count

    const bySeverity = db
      .prepare('SELECT severity, COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ? GROUP BY severity ORDER BY count DESC')
      .all(startOfDay, endOfDay) as Array<{ severity: string; count: number }>

    const byDiscipline = db
      .prepare('SELECT discipline, COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ? GROUP BY discipline ORDER BY count DESC')
      .all(startOfDay, endOfDay) as Array<{ discipline: string; count: number }>

    const topCritical = db
      .prepare("SELECT title, discipline, source_name, severity FROM intel_reports WHERE created_at >= ? AND created_at < ? AND severity IN ('critical','high') ORDER BY created_at DESC LIMIT 10")
      .all(startOfDay, endOfDay) as Array<{ title: string; discipline: string; source_name: string; severity: string }>

    const sourceCounts = db
      .prepare('SELECT source_name, COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ? GROUP BY source_name ORDER BY count DESC LIMIT 15')
      .all(startOfDay, endOfDay) as Array<{ source_name: string; count: number }>

    const sevTable = bySeverity.map((r) => `| ${r.severity.toUpperCase()} | ${r.count} |`).join('\n')
    const discTable = byDiscipline.map((r) => `| ${DISCIPLINE_LABELS[r.discipline as keyof typeof DISCIPLINE_LABELS] || r.discipline} | ${r.count} |`).join('\n')
    const critList = topCritical.map((r) => `- **[${r.severity.toUpperCase()}]** ${r.title} _(${r.discipline}, ${r.source_name})_`).join('\n')
    const sourceList = sourceCounts.map((r) => `- ${r.source_name}: ${r.count}`).join('\n')

    const md = `---
type: daily-summary
date: ${dateStr}
total_reports: ${total}
---

# Heimdall Daily Intelligence Summary — ${dateStr}

## Overview

**Total Reports Collected**: ${total}

## By Severity

| Severity | Count |
|----------|-------|
${sevTable}

## By Discipline

| Discipline | Count |
|------------|-------|
${discTable}

## Top Critical & High Priority Items

${critList || '_No critical/high items today_'}

## Top Sources

${sourceList}

---
_Generated by Heimdall Intelligence Platform_
`

    // Write to memory dir
    const dir = join(this.memoryDir, 'daily')
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, `${dateStr}.md`), md, 'utf-8')

    log.info(`Daily summary generated for ${dateStr}: ${total} reports`)
    return md
  }

  generateWeeklySummary(date?: Date): string {
    const target = date || new Date()
    const weekStart = new Date(target)
    weekStart.setDate(weekStart.getDate() - 7)
    const startTs = weekStart.getTime()
    const endTs = target.getTime()
    const weekStr = `${weekStart.toISOString().split('T')[0]}_to_${target.toISOString().split('T')[0]}`

    const db = getDatabase()

    const total = (
      db.prepare('SELECT COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ?').get(startTs, endTs) as { count: number }
    ).count

    const bySeverity = db
      .prepare('SELECT severity, COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ? GROUP BY severity')
      .all(startTs, endTs) as Array<{ severity: string; count: number }>

    const byDiscipline = db
      .prepare('SELECT discipline, COUNT(*) as count FROM intel_reports WHERE created_at >= ? AND created_at < ? GROUP BY discipline ORDER BY count DESC')
      .all(startTs, endTs) as Array<{ discipline: string; count: number }>

    const md = `---
type: weekly-summary
week: ${weekStr}
total_reports: ${total}
---

# Heimdall Weekly Intelligence Summary

**Period**: ${weekStart.toISOString().split('T')[0]} to ${target.toISOString().split('T')[0]}
**Total Reports**: ${total}

## Severity Breakdown

${bySeverity.map((r) => `- **${r.severity.toUpperCase()}**: ${r.count}`).join('\n')}

## Discipline Breakdown

${byDiscipline.map((r) => `- **${DISCIPLINE_LABELS[r.discipline as keyof typeof DISCIPLINE_LABELS] || r.discipline}**: ${r.count}`).join('\n')}

---
_Generated by Heimdall Intelligence Platform_
`
    const dir = join(this.memoryDir, 'weekly')
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, `${weekStr}.md`), md, 'utf-8')

    log.info(`Weekly summary generated for ${weekStr}: ${total} reports`)
    return md
  }
}

export const memoryService = new MemoryService()
